//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int AccountID { get; set; }
        public string Account { get; set; }
        public Nullable<int> Balans { get; set; }
        public string Currency { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
